- .github/workflows/dexios-tests.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/decrypt.rs
- src/decrypt/crypto.rs
- src/encrypt.rs
- src/encrypt/crypto.rs
- src/file.rs
- src/global.rs
- src/hashing.rs
- src/main.rs
This branch adds XChaCha20-Poly1305, along with support for more algorithms in the future (now that the groundwork has been laid out).
> Implement XChaCha20-Poly1305

- src/decrypt.rs
- src/decrypt/crypto.rs
- src/encrypt.rs
- src/encrypt/crypto.rs
- src/global.rs
- src/key.rs
- src/main.rs
- src/prompt.rs
I'm new to Rust and found this project interesting as I wanted to create something like this myself!
Added enums for more descriptive Parameter struct! And implementatons. Did not test for logic errors!
> Added enums for Parameter struct - not fully tested for logic errors!

- src/global/structs.rs
- src/header.rs
> Implement a `HeaderPrefix` struct

- .github/workflows/dexios-tests.yml
- Cargo.lock
- Cargo.toml
- src/cli.rs
- src/global/parameters.rs
- src/global/structs.rs
- src/subcommands/pack.rs
- src/subcommands/unpack.rs
Hopefully this fixes an issue specified in #50
> Implement WalkDir

- Cargo.lock
- Cargo.toml
- src/subcommands/decrypt.rs
- src/subcommands/encrypt.rs
This adds support for new things provided by `dexios-core`
It implements the features specified in #72 and #67.
> Implement V4 Header Support

- Cargo.lock
- src/cli.rs
- src/main.rs
- src/subcommands/decrypt.rs
- src/subcommands/header.rs
This function is a little barebones, as it only supports user-typed passwords.
I plan to add more functionality to it, but for now it'll do.
> Implement the option to change a key (for files using V4+ headers)

- .envrc
- .github/workflows/build_nix.yml
- default.nix
- flake.lock
- flake.nix
- shell.nix
I've added a small flake for nix users
> nix: add flake

- dexios/src/domain/overwrite.rs
- dexios/src/domain/storage.rs
- dexios/src/lib.rs
- dexios/tests/common.rs
- dexios/tests/storage.rs
Added integration tests and also fix writing mode (I forgot to add `truncate` mode)
> Add integration tests FsStorage

- dexios/src/subcommands/wordlist.lst
> chore: remove words with digits

- Cargo.lock
- Cargo.toml
- Dockerfile
- dexios-core/Cargo.toml
- dexios-core/src/cipher.rs
- dexios-core/src/header.rs
- dexios-core/src/primitives.rs
- dexios-core/src/stream.rs
- dexios/Cargo.toml
- dexios/src/global/parameters.rs
- dexios/src/main.rs
- dexios/src/subcommands/list.rs
Based on this MR #126 I made some changes :)
But we cannot disable default dependencies with `path`... so we should to update dexios-core or use `patch` section.
> core: move deoxys to feature

- Cargo.lock
- dexios/Cargo.toml
- dexios/src/cli.rs
- dexios/src/global/parameters.rs
- dexios/src/subcommands.rs
- dexios/src/subcommands/pack.rs
As a follow-up to this MR #147 
- deps: bump clap to 3.2.14
> cli/pack: add possibility to pack many files

- .github/workflows/audit.yml
- .github/workflows/cargo-build.yml
> ci: github actions improvements

- .github/workflows/cargo-build.yml
- .github/workflows/dexios-tests.yml
> ci: use matrix.os instead of runner.os

- .github/workflows/cargo-build.yml
> add warning to CI

- dexios-core/src/key.rs
https://github.com/brxken128/dexios/pull/142#issuecomment-1192879107
> core: expose vec_to_arr

- dexios-core/src/header.rs
- dexios-core/src/lib.rs
- dexios-core/src/primitives.rs
- dexios/src/domain/decrypt.rs
- dexios/src/domain/hash.rs
- dexios/src/domain/hasher.rs
- dexios/src/domain/storage.rs
- dexios/src/global/states.rs
- dexios/src/lib.rs
- dexios/src/subcommands/hashing.rs
- dexios/src/subcommands/header_key.rs
- fix clippy warnings
- handle errors in read_exact
> Cosmetic changes

- dexios-core/src/key.rs
- dexios/src/subcommands/header_key.rs
This implements the changes specified in #162.
> [HYGIENE] Implement `zeroize` for `vec_to_arr()`

- .github/workflows/unit_tests.yml
...to prevent hidden bumps from deps
> ci: add msrv to matrix

- .github/workflows/dexios-tests.yml
- dexios/src/cli.rs
- dexios/src/global/parameters.rs
- dexios/src/global/states.rs
- dexios/src/global/structs.rs
- dexios/src/main.rs
- dexios/src/subcommands/decrypt.rs
- dexios/src/subcommands/encrypt.rs
- dexios/src/subcommands/erase.rs
- dexios/src/subcommands/header.rs
- dexios/src/subcommands/key.rs
- dexios/src/subcommands/pack.rs
- dexios/src/subcommands/prompt.rs
- dexios/src/subcommands/unpack.rs
This implements the optimisations outlined in issue #184.
It removes many logging statements, and renames:
`SkipMode` (`HidePrompts` / `ShowPrompts`)
to
`ForceMode` (`Force` / `Prompt`)
> [UX] Optimisations

- dexios/src/subcommands/key.rs
Fixes #183.
I know it checks the version twice in total, but we need these validity checks within domain too.
> key/all: check header version before sourcing keys

- dexios/src/subcommands/pack.rs
> pack: prevent individual files from being packed

- Cargo.lock
- dexios-domain/src/hash.rs
- dexios/src/subcommands/pack.rs
- dexios/src/subcommands/unpack.rs
- flake.lock
- flake.nix
> cli: calculate hash after pack and unpack

- .envrc
- .gitignore
- flake.lock
- flake.nix
Add possibility to use dexios in nixos / home-manager configurations
> nix: add overlays
