brxken128/dexios

.github/workflows/dexios-tests.yml, src/cli.rs, src/decrypt/crypto.rs, src/encrypt/crypto.rs, src/hashing.rs, src/main.rs
This allows for the command `dexios hash test.txt`
It can use memory or stream mode, and implements the same checking that `encrypt.rs` and `decrypt.rs` implement to automatically detect whether or not the file should be hashed in memory or stream mode.
There are optional `-s` and `-m` switches, but `-s` will redirect you to memory mode if your file isn't large enough.
=> Implement Standalone Hashing Mode

.github/workflows/dexios-tests.yml, src/cli.rs, src/global.rs, src/header.rs, src/main.rs, src/param_handler.rs
This branch adds functions for manipulating headers created by Dexios.
It factors in the varying nonce sizes with input from the user, and is recommended for advanced users only.
These warnings are plastered around adequately.
This feature could be helpful for storing the header separate from the encrypted file (e.g. store the header on a USB drive and the file on your PC), meaning an attacker would have a **very** hard time brute-forcing the data.
=> Header Functions

Cargo.lock, Cargo.toml, src/decrypt/crypto.rs, src/encrypt/crypto.rs, src/file.rs, src/key.rs, src/main.rs, src/secret.rs
This removes the dependency on the `secrecy` crate, by implementing the same functionality ourselves.
This was done due to a mismatch in the `zeroize` versions, and it would prevent us from adding new AEADs.
=> Implement custom Secret type

Cargo.lock, Cargo.toml, src/decrypt.rs, src/decrypt/crypto.rs, src/encrypt.rs, src/encrypt/crypto.rs, src/erase.rs, src/file.rs, src/global/enums.rs, src/global/parameters.rs, src/hashing.rs, src/header.rs, src/key.rs, src/pack.rs, src/prompt.rs, src/streams.rs
This branch **heavily** improves the output to the terminal provided by Dexios. The changes are rather shocking, and I don't know why I never had the idea to implement them sooner.
=> Implement paris crate to cleanup command-line output

src/crypto/decrypt.rs, src/crypto/encrypt.rs, src/subcommands/decrypt.rs, src/subcommands/encrypt.rs
This branch delegates `-H` to the dedicated hash command, as opposed to doing it within `encrypt_bytes_x` or `decrypt_bytes_x`.
=> Remove hashing from crypto functions

.github/workflows/dexios-tests.yml, Cargo.lock, Cargo.toml, SECURITY.md, src/cli.rs, src/file.rs, src/global/parameters.rs, src/global/states.rs, src/global/structs.rs, src/main.rs, src/subcommands.rs, src/subcommands/pack.rs, src/subcommands/unpack.rs
This branch adds a revamped pack/unpack mode.
There are more zip-slip protections, and the syntax has been improved dramatically.
`dexios pack directory/ file.enc` and `dexios unpack file.enc .` can be used for seamless packing/encrypting, and unpacking/decrypting.
=> Add Pack Mode

src/subcommands/pack.rs
This fixes the issue mentioned in #50 - it's very annoying and was hard to debug.
The `zip` crate was treating `\` as a random character, and it was causing everything to be messed up.
It was a rather simple fix, but if the running OS is Windows, replace all `\` characters in the path with `/`.
I'm going to test the `unpack` functionality further, but I believe this issue should be fixed.
=> fix annoying zip/windows issue

Cargo.lock, Cargo.toml, src/cli.rs, src/global/parameters.rs, src/global/states.rs, src/global/structs.rs, src/subcommands/decrypt.rs, src/subcommands/encrypt.rs, src/subcommands/pack.rs
This branch adds a `-z` switch to `pack` mode.
It uses the `zip` crate's defaults (ZSTD compression level = 3), and I have confirmed it to be fully working.
Your mileage will vary depending on the entropy of the files you are packing - high entropy means less room for compression.
I would **not** recommend using `-z` to pack already-encrypted files. There are no benefits to that.
This implements #79.
=> Compression support

.github/workflows/dexios-tests.yml, src/cli.rs, src/global/parameters.rs, src/global/states.rs, src/global/structs.rs, src/subcommands.rs, src/subcommands/decrypt.rs, src/subcommands/encrypt.rs, src/subcommands/header.rs, src/subcommands/unpack.rs
This refactors how detached headers are handled, and implements support for encrypting and storing the header elsewhere.
The header will never be written with the encrypted data, if `--header` and a different file/path is supplied.
You will need to either use `dexios header restore`, or decrypt with a detached header in order to decrypt your data.
This relates to #73.
=> Detached Header Rework

Cargo.lock, dexios-core/Cargo.toml, dexios-core/src/key.rs
With the release of balloon-hash v0.3.0, `hash_into` was provided as a function you may use to prevent reallocation. This means we no longer need to manually `zeroize` everything the hashed key has touched.
=> Migrate to `hash_into`

dexios/src/cli.rs
You forgot to remove password from `pack` and `unpack` commands
mentioned #100
=> cli: remove password option from pack and unpack

dexios/src/cli.rs
I've started working on task #99 and found this problem. I cannot run `pack` subcommand on the master.
```
thread 'main' panicked at 'Command pack: Argument names must be unique, but 'erase' is in use by more than one argument or group', /home/janabhumi/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/builder/debug_asserts.rs:100:9
stack backtrace:
0: rust_begin_unwind
1: core::panicking::panic_fmt
2: clap::builder::debug_asserts::assert_app
at /home/janabhumi/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/builder/debug_asserts.rs:100:9
3: clap::builder::command::App::_build_self
at /home/janabhumi/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.2.8/src/builder/command.rs:4300:13
4: clap::builder::command::App::_build_subcommand
at …
```
=> cli: fix executing pack command

dexios-core/src/key.rs, dexios/src/subcommands.rs, dexios/src/subcommands/decrypt.rs, dexios/src/subcommands/encrypt.rs, dexios/src/subcommands/hashing.rs, dexios/src/subcommands/pack.rs
Moved path validation above. Added zip archive cleanup on encryption error.
I want to move password retrieval from encryption, but it will take more time and effort)
=> cli/pack: erase temp file on failure

dexios-core/src/cipher.rs, dexios-core/src/key.rs, dexios-core/src/stream.rs, dexios/src/domain/mod.rs, dexios/src/domain/overwrite.rs, dexios/src/main.rs, dexios/src/subcommands/decrypt.rs, dexios/src/subcommands/encrypt.rs, dexios/src/subcommands/erase.rs, dexios/src/subcommands/hashing.rs, dexios/src/subcommands/header.rs, dexios/src/subcommands/list.rs
- renamed `domain/erase` to `domain/overwrite`. I'll add a canonical erase later, which will use overwrite itself.
- changed all `match` patterns that are used as `mar_err`
- added copy_from_slice instead of a manual copy loop
=> Improvements

dexios/src/domain/erase.rs, dexios/src/domain/mod.rs, dexios/src/domain/overwrite.rs, dexios/src/domain/storage.rs, dexios/src/subcommands/erase.rs
=> domain/erase: extract base logic of the erase command

dexios/src/subcommands/key.rs
This will probably fix #103, but I can't check it.
=> cli: some improvements for password

Cargo.lock, dexios-core/src/cipher.rs, dexios-core/src/header.rs, dexios-core/src/key.rs, dexios-core/src/primitives.rs, dexios-core/src/protected.rs, dexios/Cargo.toml, dexios/src/cli.rs, dexios/src/global/parameters.rs, dexios/src/main.rs, dexios/src/subcommands.rs, dexios/src/subcommands/decrypt.rs, dexios/src/subcommands/encrypt.rs, dexios/src/subcommands/header.rs, dexios/src/subcommands/header_key.rs
This is nowhere near done, at all.
I'm going to mark it as a draft for now - there's a **lot** to do. I need to:
* Read the actual information itself from the header
* Ensure that it can be done in a backwards-compatible manner
* Handle serialization of the headers (and AAD creation)
* Update the CLI app's functions (most notably the change password one)
* Probably some more
There are a lot of things needed for this to work correctly - hopefully it's not too bad.
=> header: implement v5 headers

.github/workflows/dexios-tests.yml, dexios-core/src/primitives.rs, dexios/src/global/parameters.rs, dexios/src/subcommands/list.rs
This adds explicit disallowing of Deoxys for encryption, however decryption will still be supported.
This fixes #116.
=> Depreciate Deoxys Encryption

.gitignore, dexios-core/src/primitives.rs
This will be better than the previous solution, because we can add more features to the algorithms without headache!
let's imagine that we have 2 features... how should we implement them?
```rust
#[cfg(not(all(feature = "1", feature = "2")))]
const LEN = 2;
#[cfg(any(all(feature = "1", not(feature = "2")), all(not(feature = "1"), feature = "2"))))]
const LEN = 3;
#[cfg(all(feature = "1", feature = "2"))]
const LEN = 4;
```
what about 3 features?))
another way is
```rust
#[cfg(features = "1")]
const DEOXYS_ENABLED: usize = 1;
#[cfg(not(features = "1"))]
const DEOXYS_ENABLED: usize = 0;
#[cfg(feature = "2")]
const ANOTHER_ENABLED: usize = 1;
#[cfg(not(feature = "2"))]
const ANOTHER_ENABLED: usize = 0;
const LEN: usize = 2 + DEOXYS_ENABLED + ANOTHER_ENABLED;
```
Better! Easy to maintain, but …
=> core: use const fn instead of vars

.dockerignore, Cargo.lock, Cargo.toml, Dockerfile, dexios-core/src/protected.rs, dexios/Cargo.toml, dexios/src/file.rs, dexios/src/global/states.rs
A small change from me. I'm currently using this program roughly as shown in the following example:
```sh
DEXIOS_KEY=$(pass show dexios/finance) dexios -py business business.enc 
```
This changes make it possible to use the password manager directly
```sh
pass show dexios/finance | dexios -pyk - business business.enc
```
or read keyfile and pipe to program
```sh
cat mykeyfile | dexios -pyk - business business.enc
```
=> cli: add stdin support for the keyfile param

dexios/src/global/parameters.rs
The clap update seems to have broken our decrypt command.
```
➜  dexios git:(master) ✗ cargo run -- decrypt flake.enc flake.orig
thread 'main' panicked at '`autogenerate` is not an id of an argument or a group.
Make sure you're using the name of the argument itself and not the name of short or long flags.', dexios/src/global/parameters.rs:34:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
=> cli/decrypt: fix matching autogenerate arg

.github/workflows/cargo-build.yml, dexios-core/src/key.rs, dexios-core/src/primitives.rs, dexios/src/utils.rs
Although the changes are pretty trivial, this should provide additional protection from certain side-channel attacks.
I implemented this for things that need it the most: the salt, nonce, and master key.
The discussion regarding this can be found in #135.
`gen_salt()` and `gen_master_key()` were also moved into `primitives.rs`, to keep things uniform and in one place.
=> Migrate to `ThreadRng` from `StdRng`

Cargo.lock, dexios-core/Cargo.toml, dexios-core/src/lib.rs, dexios-core/src/stream.rs, dexios-core/src/visual.rs, dexios/Cargo.toml
Due to the design of our current codebase, a progress *bar* would be quite unfeasible as we'd need to get and pass the file size down a multitude of functions. I like how our codebase stands currently, and I don't think this one feature warrants that amount of effort/refactoring.
With that, I've decided to implement a progress *spinner*. It's not as descriptive as a bar, but at least it lets the user know that things are still happening. I feel like this is a good compromise between the two.
This is related to #102.
(despite it not being a progress bar, I think it adds a nice touch for larger files/slow computers)
This also adds the `visual` feature to dexios-core, and that will pull in `indicatif` and display the spinner on stream encrypt/decrypt automatically (when the …
=> [FEATURE] Add a progress spinner

dexios/src/subcommands/decrypt.rs
It wasn't in [original](https://github.com/brxken128/dexios/pull/140/files#diff-34f6e48baa077b22449fa179834d96884d5854c2b280fc6676e9152424e887d3L145). Seems that I took this from the encrypt command)
=> cli/decrypt: remove the tragic copy-paste error

.github/workflows/cargo-build.yml, .github/workflows/unit_tests.yml
...because fails affect our "build" badge
=> ci: move the unit tests to a separate file

dexios-core/src/header.rs, dexios-core/src/key.rs, dexios/src/subcommands/header_key.rs
This implements everything mentioned by the following command:
`cargo clippy --all -- -W clippy::pedantic -W clippy::correctness -W clippy::perf -W clippy::style -W clippy::suspicious -W clippy::complexity -D warnings`.
I have not resolved the doc errors, as they're likely to change and not currently a priority.
=> [CLIPPY] Implement `clippy` lints

dexios/src/global/parameters.rs, dexios/src/global/states.rs, dexios/src/main.rs
This closes #163 and cleans up the codebase a lot.
I decided to require the specification of `"keyfile"`, as the key manipulation functions need alternate descriptors (`"keyfile-old"` and `"keyfile-new"`).
=> [KEY] Add `init` function

Cargo.toml, dexios-domain/Cargo.toml, dexios-domain/README.md
The move to `domain` should be relatively soon, so it makes sense to add a workspace member for it.
Either way, I have [published it to crates.io](https://crates.io/crates/dexios-domain).
The actual migration will be a large task, and I don't mind doing it myself provided the majority of the core logic has been isolated (it has!)
=> [CRATE] Adds a base layout for the `domain` crate

.github/workflows/unit_tests.yml
This is so we don't get failing tests on every PR actions run.
I assume the error is within our unit tests, and probably something to do with Windows paths (and how abysmal they are in relation to every other OS). It will get fixed at some point, but for the time being I suggest we just disable it.
This will also prevent email spam for every commit on every PR (my inbox will greatly appreciate it!)
=> ci: disable windows unit tests temporarily

Cargo.lock, dexios/Cargo.toml, dexios/src/subcommands/header.rs
This is part of our cleanup, specified in #171.
This just uses a simple conversion function from `&[u8]` to hex, via `format!()`.
It's private as there's nowhere else in the codebase that currently uses it, aside from `header/details`. There's probably a better place for it though.
=> [DEPS] Remove `hex` dependency

Cargo.lock, dexios/Cargo.toml, dexios/src/cli.rs, dexios/src/global.rs, dexios/src/global/parameters.rs, dexios/src/global/states.rs, dexios/src/subcommands/decrypt.rs, dexios/src/subcommands/encrypt.rs, dexios/src/subcommands/erase.rs, dexios/src/subcommands/hashing.rs, dexios/src/subcommands/header.rs, dexios/src/subcommands/header_key.rs, dexios/src/subcommands/key.rs, dexios/src/subcommands/pack.rs, dexios/src/subcommands/prompt.rs, dexios/src/subcommands/unpack.rs
This PR removes our reliance on `paris`.
It does not have fancy colours and icons, but we can always add those later on (at least the colours).
It just uses a set of 5 macros which format the statement, print and prefix `[!]` or similar to the start.
There are 5 potential prefixes:
* `[?]` for questions
* `[i]` for information
* `[!]` for errors
* `[-]` for warnings
* `[+]` for successes
=> [DEPS] Remove `paris` dependency

dexios-domain/src/hash.rs, dexios-domain/src/pack.rs
It looks as though while moving to `domain`, something was incorrectly copied over and we were allocating a full 1MiB array on the stack. Windows' stack size is considerably smaller than other OSes, such as Linux, so this issue slipped through the cracks.
=> pack+mem: fix stack overflow issues

dexios-core/src/header.rs, dexios-core/src/key.rs, dexios-core/src/lib.rs, dexios-core/src/visual.rs, dexios-domain/src/erase.rs, dexios-domain/src/erase_dir.rs, dexios-domain/src/key.rs, dexios-domain/src/key/add.rs, dexios-domain/src/key/change.rs, dexios-domain/src/key/delete.rs, dexios-domain/src/key/verify.rs, dexios-domain/src/lib.rs, dexios-domain/src/overwrite.rs, dexios/src/cli.rs, dexios/src/main.rs, dexios/src/subcommands.rs, dexios/src/subcommands/key.rs
This closes #228.
It allows a user to verify that a key is correct, without decrypting the entire file/piping the output to `/dev/null`. This also has the added benefit of working across multiple platforms.
It only supports V5 headers and above, as I think it's impractical for others (V3 and below would require the data to also be present).
=> feature: add key verification

dexios-core/src/key.rs, dexios/src/cli.rs, dexios/src/global/parameters.rs, dexios/src/global/states.rs
This implements some changes mentioned in the [PrivacyGuides discussion](https://github.com/privacyguides/privacyguides.org/discussions/1352#discussioncomment-3675030) for Dexios.
New passphrases will now be in the format of: `word-word-word-word-word-word-word` (with the amount of words being customizable). This can be done with `dexios encrypt --auto=n`, where `n` is the amount of words.
=> core: tweak passphrase autogeneration

README.md
When some time has passed since the release of a program, new dependencies can prevent cargo from building that application. The `--locked` flag forces cargo to build the application with the original dependencies in which it was released. Changing to a block of code allows you to copy it with the button on the right.
=> Adding locked
